#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinqQuinto")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Productos(Tbl_Productos instance);
    partial void UpdateTbl_Productos(Tbl_Productos instance);
    partial void DeleteTbl_Productos(Tbl_Productos instance);
    partial void InsertTbl_proveedor(Tbl_proveedor instance);
    partial void UpdateTbl_proveedor(Tbl_proveedor instance);
    partial void DeleteTbl_proveedor(Tbl_proveedor instance);
    partial void InsertTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void UpdateTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void DeleteTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void InsertTbl_Usuarios(Tbl_Usuarios instance);
    partial void UpdateTbl_Usuarios(Tbl_Usuarios instance);
    partial void DeleteTbl_Usuarios(Tbl_Usuarios instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.LinqQuintoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Productos> Tbl_Productos
		{
			get
			{
				return this.GetTable<Tbl_Productos>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_proveedor> Tbl_proveedor
		{
			get
			{
				return this.GetTable<Tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_TipoUsuario> Tbl_TipoUsuario
		{
			get
			{
				return this.GetTable<Tbl_TipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Usuarios> Tbl_Usuarios
		{
			get
			{
				return this.GetTable<Tbl_Usuarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Productos")]
	public partial class Tbl_Productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<char> _pro_estado;
		
		private int _prov_id;
		
		private EntityRef<Tbl_proveedor> _Tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    #endregion
		
		public Tbl_Productos()
		{
			this._Tbl_proveedor = default(EntityRef<Tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(100)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int NOT NULL")]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._Tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_proveedor_Tbl_Productos", Storage="_Tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public Tbl_proveedor Tbl_proveedor
		{
			get
			{
				return this._Tbl_proveedor.Entity;
			}
			set
			{
				Tbl_proveedor previousValue = this._Tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_proveedor.Entity = null;
						previousValue.Tbl_Productos.Remove(this);
					}
					this._Tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.Tbl_Productos.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(int);
					}
					this.SendPropertyChanged("Tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_proveedor")]
	public partial class Tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private EntitySet<Tbl_Productos> _Tbl_Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public Tbl_proveedor()
		{
			this._Tbl_Productos = new EntitySet<Tbl_Productos>(new Action<Tbl_Productos>(this.attach_Tbl_Productos), new Action<Tbl_Productos>(this.detach_Tbl_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(100)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_proveedor_Tbl_Productos", Storage="_Tbl_Productos", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<Tbl_Productos> Tbl_Productos
		{
			get
			{
				return this._Tbl_Productos;
			}
			set
			{
				this._Tbl_Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Productos(Tbl_Productos entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_proveedor = this;
		}
		
		private void detach_Tbl_Productos(Tbl_Productos entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_TipoUsuario")]
	public partial class Tbl_TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TUsu_id;
		
		private string _TUu_Nombre;
		
		private System.Nullable<char> _TUsu_estado;
		
		private EntitySet<Tbl_Usuarios> _Tbl_Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTUsu_idChanging(int value);
    partial void OnTUsu_idChanged();
    partial void OnTUu_NombreChanging(string value);
    partial void OnTUu_NombreChanged();
    partial void OnTUsu_estadoChanging(System.Nullable<char> value);
    partial void OnTUsu_estadoChanged();
    #endregion
		
		public Tbl_TipoUsuario()
		{
			this._Tbl_Usuarios = new EntitySet<Tbl_Usuarios>(new Action<Tbl_Usuarios>(this.attach_Tbl_Usuarios), new Action<Tbl_Usuarios>(this.detach_Tbl_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUsu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TUsu_id
		{
			get
			{
				return this._TUsu_id;
			}
			set
			{
				if ((this._TUsu_id != value))
				{
					this.OnTUsu_idChanging(value);
					this.SendPropertyChanging();
					this._TUsu_id = value;
					this.SendPropertyChanged("TUsu_id");
					this.OnTUsu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUu_Nombre", DbType="VarChar(50)")]
		public string TUu_Nombre
		{
			get
			{
				return this._TUu_Nombre;
			}
			set
			{
				if ((this._TUu_Nombre != value))
				{
					this.OnTUu_NombreChanging(value);
					this.SendPropertyChanging();
					this._TUu_Nombre = value;
					this.SendPropertyChanged("TUu_Nombre");
					this.OnTUu_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUsu_estado", DbType="Char(1)")]
		public System.Nullable<char> TUsu_estado
		{
			get
			{
				return this._TUsu_estado;
			}
			set
			{
				if ((this._TUsu_estado != value))
				{
					this.OnTUsu_estadoChanging(value);
					this.SendPropertyChanging();
					this._TUsu_estado = value;
					this.SendPropertyChanged("TUsu_estado");
					this.OnTUsu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuarios", Storage="_Tbl_Usuarios", ThisKey="TUsu_id", OtherKey="TUsu_id")]
		public EntitySet<Tbl_Usuarios> Tbl_Usuarios
		{
			get
			{
				return this._Tbl_Usuarios;
			}
			set
			{
				this._Tbl_Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Usuarios(Tbl_Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario = this;
		}
		
		private void detach_Tbl_Usuarios(Tbl_Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuarios")]
	public partial class Tbl_Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_cedula;
		
		private string _usu_nombre;
		
		private string _usu_apellido;
		
		private string _usu_direccion;
		
		private string _usu_telefono;
		
		private System.Nullable<System.DateTime> _usu_fechacreacion;
		
		private string _usu_contraseña;
		
		private string _usu_nomlogin;
		
		private System.Nullable<char> _usu_estado;
		
		private string _usu_correo;
		
		private int _TUsu_id;
		
		private EntityRef<Tbl_TipoUsuario> _Tbl_TipoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_apellidoChanging(string value);
    partial void Onusu_apellidoChanged();
    partial void Onusu_direccionChanging(string value);
    partial void Onusu_direccionChanged();
    partial void Onusu_telefonoChanging(string value);
    partial void Onusu_telefonoChanged();
    partial void Onusu_fechacreacionChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fechacreacionChanged();
    partial void Onusu_contraseñaChanging(string value);
    partial void Onusu_contraseñaChanged();
    partial void Onusu_nomloginChanging(string value);
    partial void Onusu_nomloginChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void OnTUsu_idChanging(int value);
    partial void OnTUsu_idChanged();
    #endregion
		
		public Tbl_Usuarios()
		{
			this._Tbl_TipoUsuario = default(EntityRef<Tbl_TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string usu_apellido
		{
			get
			{
				return this._usu_apellido;
			}
			set
			{
				if ((this._usu_apellido != value))
				{
					this.Onusu_apellidoChanging(value);
					this.SendPropertyChanging();
					this._usu_apellido = value;
					this.SendPropertyChanged("usu_apellido");
					this.Onusu_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direccion", DbType="VarChar(100)")]
		public string usu_direccion
		{
			get
			{
				return this._usu_direccion;
			}
			set
			{
				if ((this._usu_direccion != value))
				{
					this.Onusu_direccionChanging(value);
					this.SendPropertyChanging();
					this._usu_direccion = value;
					this.SendPropertyChanged("usu_direccion");
					this.Onusu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_telefono", DbType="VarChar(10)")]
		public string usu_telefono
		{
			get
			{
				return this._usu_telefono;
			}
			set
			{
				if ((this._usu_telefono != value))
				{
					this.Onusu_telefonoChanging(value);
					this.SendPropertyChanging();
					this._usu_telefono = value;
					this.SendPropertyChanged("usu_telefono");
					this.Onusu_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fechacreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fechacreacion
		{
			get
			{
				return this._usu_fechacreacion;
			}
			set
			{
				if ((this._usu_fechacreacion != value))
				{
					this.Onusu_fechacreacionChanging(value);
					this.SendPropertyChanging();
					this._usu_fechacreacion = value;
					this.SendPropertyChanged("usu_fechacreacion");
					this.Onusu_fechacreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contraseña", DbType="VarChar(50)")]
		public string usu_contraseña
		{
			get
			{
				return this._usu_contraseña;
			}
			set
			{
				if ((this._usu_contraseña != value))
				{
					this.Onusu_contraseñaChanging(value);
					this.SendPropertyChanging();
					this._usu_contraseña = value;
					this.SendPropertyChanged("usu_contraseña");
					this.Onusu_contraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nomlogin", DbType="VarChar(50)")]
		public string usu_nomlogin
		{
			get
			{
				return this._usu_nomlogin;
			}
			set
			{
				if ((this._usu_nomlogin != value))
				{
					this.Onusu_nomloginChanging(value);
					this.SendPropertyChanging();
					this._usu_nomlogin = value;
					this.SendPropertyChanged("usu_nomlogin");
					this.Onusu_nomloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(40)")]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUsu_id", DbType="Int NOT NULL")]
		public int TUsu_id
		{
			get
			{
				return this._TUsu_id;
			}
			set
			{
				if ((this._TUsu_id != value))
				{
					if (this._Tbl_TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTUsu_idChanging(value);
					this.SendPropertyChanging();
					this._TUsu_id = value;
					this.SendPropertyChanged("TUsu_id");
					this.OnTUsu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuarios", Storage="_Tbl_TipoUsuario", ThisKey="TUsu_id", OtherKey="TUsu_id", IsForeignKey=true)]
		public Tbl_TipoUsuario Tbl_TipoUsuario
		{
			get
			{
				return this._Tbl_TipoUsuario.Entity;
			}
			set
			{
				Tbl_TipoUsuario previousValue = this._Tbl_TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_TipoUsuario.Entity = null;
						previousValue.Tbl_Usuarios.Remove(this);
					}
					this._Tbl_TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuarios.Add(this);
						this._TUsu_id = value.TUsu_id;
					}
					else
					{
						this._TUsu_id = default(int);
					}
					this.SendPropertyChanged("Tbl_TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
